name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          yarn
          yarn lint
          mkdir -p ~/.ssh
          ssh-keyscan -H '34.124.205.242'  >> ~/.ssh/known_hosts
          echo "${{secrets.PRIVATE_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{secrets.ENV}}" > .env
          yarn build:prod
          cd ./public && rsync --progress -avzh -e "ssh -i ~/.ssh/id_rsa " --rsync-path="sudo rsync" . ubuntu@34.124.205.242:/var/www/html
